name: Liteium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        pip install liteium

    - name: Download ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -N https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run tests
      env:
        PATH: /usr/local/bin:$PATH
      run: |
        pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
